// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWYWz0Yaug-a3krsD71T2HZE2CWzSRusM',
    appId: '1:903677145089:web:549d277005a4b684275000',
    messagingSenderId: '903677145089',
    projectId: 'tcmv4-fea0b',
    authDomain: 'tcmv4-fea0b.firebaseapp.com',
    storageBucket: 'tcmv4-fea0b.appspot.com',
    measurementId: 'G-DXE72XH4MN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkV_AY-zKOyZcAmA8Uu8p2K9HdMjL5pmw',
    appId: '1:903677145089:android:8caff767c0e3b513275000',
    messagingSenderId: '903677145089',
    projectId: 'tcmv4-fea0b',
    storageBucket: 'tcmv4-fea0b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZhck7vnkpBKZaJwwqzYoww48qFfVTwwA',
    appId: '1:903677145089:ios:74178f0436671bd9275000',
    messagingSenderId: '903677145089',
    projectId: 'tcmv4-fea0b',
    storageBucket: 'tcmv4-fea0b.appspot.com',
    androidClientId: '903677145089-0vl15msp1g2ljn50pguen6kj1p5eag2l.apps.googleusercontent.com',
    iosClientId: '903677145089-srsr32ntmnt5oqvl8up7u619k738m0fn.apps.googleusercontent.com',
    iosBundleId: 'com.aikampo.app.ios',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZhck7vnkpBKZaJwwqzYoww48qFfVTwwA',
    appId: '1:903677145089:ios:2d9523db4a22dc9c275000',
    messagingSenderId: '903677145089',
    projectId: 'tcmv4-fea0b',
    storageBucket: 'tcmv4-fea0b.appspot.com',
    androidClientId: '903677145089-0vl15msp1g2ljn50pguen6kj1p5eag2l.apps.googleusercontent.com',
    iosClientId: '903677145089-ll0k5a7etiucj81h7tj55ucu8orefnus.apps.googleusercontent.com',
    iosBundleId: 'com.aikampo.aiKampoAppPhase1',
  );
}
