// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXNYrmlKZh1fT92l2m39z6EjlBehZ1erg',
    appId: '1:982447607474:web:1938fd3cbfc18d345743ab',
    messagingSenderId: '982447607474',
    projectId: 'tcmmobile01',
    authDomain: 'tcmmobile01.firebaseapp.com',
    storageBucket: 'tcmmobile01.appspot.com',
    measurementId: 'G-58Z1NV12VT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQC7C4p1RJGvt3mszGu-Bpuc7YWeskn58',
    appId: '1:982447607474:android:ad02710fffd004c85743ab',
    messagingSenderId: '982447607474',
    projectId: 'tcmmobile01',
    storageBucket: 'tcmmobile01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY-kYduN7QwjeGwUBWiMN0RkaHaB8xaSY',
    appId: '1:982447607474:ios:97df7c339aca5ba95743ab',
    messagingSenderId: '982447607474',
    projectId: 'tcmmobile01',
    storageBucket: 'tcmmobile01.appspot.com',
    androidClientId: '982447607474-q3fp9c31vb5b7vtnnlfr4u39fqvg9gif.apps.googleusercontent.com',
    iosClientId: '982447607474-tohvc3uean54lr76cprirm6lo38ej1ln.apps.googleusercontent.com',
    iosBundleId: 'com.aikampo.app.ios',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBY-kYduN7QwjeGwUBWiMN0RkaHaB8xaSY',
    appId: '1:982447607474:ios:6ffdd409ce2bdf8d5743ab',
    messagingSenderId: '982447607474',
    projectId: 'tcmmobile01',
    storageBucket: 'tcmmobile01.appspot.com',
    androidClientId: '982447607474-q3fp9c31vb5b7vtnnlfr4u39fqvg9gif.apps.googleusercontent.com',
    iosClientId: '982447607474-rnqa068gkojftc4qr36d4ssmo1eh8gav.apps.googleusercontent.com',
    iosBundleId: 'com.aikampo.aiKampoAppPhase1',
  );
}
